services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecomdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cdn:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ..uploads:/var/www/uploads
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_container
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 1000
      MP_MAX_MESSAGE_SIZE: 10mb
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - localstack
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ecomdb
      - DB_SSLMODE=disable
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_BUCKET_NAME=ecom-uploads
      - AWS_EVENT_QUEUE_NAME=ecom-events
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@shop.com
      - JWT_SECRET=mysecretkey
      - GIN_MODE=release
      - UPLOAD_PROVIDER=local
      - UPLOAD_PATH=./uploads
    command: [ "./api" ]

  notifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - localstack
      - mailpit
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ecomdb
      - DB_SSLMODE=disable
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_BUCKET_NAME=ecom-uploads
      - AWS_EVENT_QUEUE_NAME=ecom-events
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@shop.com
    command: [ "./notifier" ]
    deploy:
      replicas: 1

volumes:
  postgres_data:
  localstack_data:
  mailpit_data: