### Update authenticated user's profile
PUT {{base_url}}/users/profile
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "first_name": "Ram",
  "last_name": "Shrestha",
  "phone": "9800000000"
}
