package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/NR3101/go-ecom-project/graph"
	"github.com/NR3101/go-ecom-project/graph/model"
	"github.com/NR3101/go-ecom-project/internal/dto"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input dto.RegisterRequest) (*dto.AuthResponse, error) {
	res, err := r.authService.Register(&input)
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	return res, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input dto.LoginRequest) (*dto.AuthResponse, error) {
	res, err := r.authService.Login(&input)
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	return res, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input dto.RefreshTokenRequest) (*dto.AuthResponse, error) {
	res, err := r.authService.RefreshToken(&input)
	if err != nil {
		return nil, fmt.Errorf("token refresh failed: %w", err)
	}

	return res, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input dto.RefreshTokenRequest) (bool, error) {
	err := r.authService.Logout(input.RefreshToken)
	if err != nil {
		return false, fmt.Errorf("logout failed: %w", err)
	}

	return true, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input dto.UpdateProfileRequest) (*dto.UserResponse, error) {
	userID, err := GetUserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	res, err := r.userService.UpdateProfile(userID, &input)
	if err != nil {
		return nil, fmt.Errorf("profile update failed: %w", err)
	}

	return res, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	if !IsAdmin(ctx) {
		return nil, ErrUnauthorized
	}

	res, err := r.productService.CreateCategory(&input)
	if err != nil {
		return nil, fmt.Errorf("category creation failed: %w", err)
	}

	return res, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input dto.UpdateCategoryRequest) (*dto.CategoryResponse, error) {
	if !IsAdmin(ctx) {
		return nil, ErrUnauthorized
	}

	parseId, err := r.parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID: %w", err)
	}

	res, err := r.productService.UpdateCategory(parseId, &input)
	if err != nil {
		return nil, fmt.Errorf("category update failed: %w", err)
	}

	return res, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	if !IsAdmin(ctx) {
		return false, ErrUnauthorized
	}

	parseId, err := r.parseID(id)
	if err != nil {
		return false, fmt.Errorf("invalid category ID: %w", err)
	}

	err = r.productService.DeleteCategory(parseId)
	if err != nil {
		return false, fmt.Errorf("category deletion failed: %w", err)
	}

	return true, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input dto.CreateProductRequest) (*dto.ProductResponse, error) {
	if !IsAdmin(ctx) {
		return nil, ErrUnauthorized
	}

	res, err := r.productService.CreateProduct(&input)
	if err != nil {
		return nil, fmt.Errorf("product creation failed: %w", err)
	}

	return res, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input dto.UpdateProductRequest) (*dto.ProductResponse, error) {
	if !IsAdmin(ctx) {
		return nil, ErrUnauthorized
	}

	parseId, err := r.parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	res, err := r.productService.UpdateProduct(parseId, &input)
	if err != nil {
		return nil, fmt.Errorf("product update failed: %w", err)
	}

	return res, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if !IsAdmin(ctx) {
		return false, ErrUnauthorized
	}

	parseId, err := r.parseID(id)
	if err != nil {
		return false, fmt.Errorf("invalid product ID: %w", err)
	}

	err = r.productService.DeleteProduct(parseId)
	if err != nil {
		return false, fmt.Errorf("product deletion failed: %w", err)
	}

	return true, nil
}

// AddToCart is the resolver for the addToCart field.
func (r *mutationResolver) AddToCart(ctx context.Context, input dto.AddToCartRequest) (*dto.CartResponse, error) {
	panic(fmt.Errorf("not implemented: AddToCart - addToCart"))
}

// UpdateCartItem is the resolver for the updateCartItem field.
func (r *mutationResolver) UpdateCartItem(ctx context.Context, cartItemID string, input dto.UpdateCartItemRequest) (*dto.CartResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateCartItem - updateCartItem"))
}

// RemoveCartItem is the resolver for the removeCartItem field.
func (r *mutationResolver) RemoveCartItem(ctx context.Context, cartItemID string) (*dto.CartResponse, error) {
	panic(fmt.Errorf("not implemented: RemoveCartItem - removeCartItem"))
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context) (*dto.OrderResponse, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.UserResponse, error) {
	userID, err := GetUserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get user ID from context: %w", err)
	}

	res, err := r.userService.GetProfile(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user profile: %w", err)
	}

	return res, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, page *int, limit *int) (*model.ProductConnection, error) {
	p := 1
	l := 10
	if page != nil {
		p = *page
	}
	if limit != nil {
		l = *limit
	}

	products, meta, err := r.productService.GetProducts(p, l)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch products: %w", err)
	}

	edges := make([]*model.ProductEdge, len(products))
	for i, product := range products {
		edges[i] = &model.ProductEdge{
			Node: &product,
		}
	}

	return &model.ProductConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			Page:       meta.Page,
			Limit:      meta.Limit,
			Total:      int(meta.Total),
			TotalPages: meta.TotalPages,
		},
	}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*dto.ProductResponse, error) {
	parseId, err := r.parseID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	res, err := r.productService.GetProduct(parseId)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch product: %w", err)
	}

	return res, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*dto.CategoryResponse, error) {
	categories, err := r.productService.GetCategories()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch categories: %w", err)
	}

	res := make([]*dto.CategoryResponse, len(categories))
	for i, category := range categories {
		res[i] = &category
	}

	return res, nil
}

// Cart is the resolver for the cart field.
func (r *queryResolver) Cart(ctx context.Context) (*dto.CartResponse, error) {
	panic(fmt.Errorf("not implemented: Cart - cart"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, page *int, limit *int) (*model.OrderConnection, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*dto.OrderResponse, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
